# Generated by Django 5.1.7 on 2025-04-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('products', '0002_alter_product_options_product_implementer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='implementer',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='companies.company', verbose_name='Реализатор'),
        ),
    ]
